// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYEZw55G4SogDM2qPZm3CjVIoLFQnQ89I',
    appId: '1:390982908203:android:c694915d3ef9f5bb9ced6e',
    messagingSenderId: '390982908203',
    projectId: 'fcfanclub-6e513',
    storageBucket: 'fcfanclub-6e513.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBys2k6AQ6h0lMj6PYyrPFw4YqoZGcX_0E',
    appId: '1:390982908203:ios:43af1f7aea6163ec9ced6e',
    messagingSenderId: '390982908203',
    projectId: 'fcfanclub-6e513',
    storageBucket: 'fcfanclub-6e513.appspot.com',
    androidClientId: '390982908203-avv510plbjmqm3a4aokra0g210f7sblj.apps.googleusercontent.com',
    iosClientId: '390982908203-un84au0gau2783rep3551dkc2ucqn9ko.apps.googleusercontent.com',
    iosBundleId: 'com.pue.fcfanclub',
  );
}
